<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="1" failed="1" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-03-03T15:54:55 IST" name="SuiteScreenshot" finished-at="2022-03-03T15:55:57 IST" duration-ms="62436">
    <groups>
    </groups>
    <test started-at="2022-03-03T15:54:55 IST" name="TestScreenshot" finished-at="2022-03-03T15:55:57 IST" duration-ms="62436">
      <class name="com.qa.testCases.LoginPageTestScenario2">
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.qa.testCases.LoginPageTestScenario2@694abbdc]" started-at="2022-03-03T15:54:55 IST" name="setup" finished-at="2022-03-03T15:55:10 IST" duration-ms="15205" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginWithCorrectIDPass()[pri:1, instance:com.qa.testCases.LoginPageTestScenario2@694abbdc]" started-at="2022-03-03T15:55:10 IST" name="loginWithCorrectIDPass" finished-at="2022-03-03T15:55:27 IST" duration-ms="16909" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithCorrectIDPass -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.testCases.LoginPageTestScenario2@694abbdc]" started-at="2022-03-03T15:55:27 IST" name="tearDown" finished-at="2022-03-03T15:55:28 IST" duration-ms="787" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
        <test-method is-config="true" signature="setup(java.lang.String)[pri:0, instance:com.qa.testCases.LoginPageTestScenario2@694abbdc]" started-at="2022-03-03T15:55:28 IST" name="setup" finished-at="2022-03-03T15:55:44 IST" duration-ms="16741" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[Chrome]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method signature="loginWithIncorrectID()[pri:2, instance:com.qa.testCases.LoginPageTestScenario2@694abbdc]" started-at="2022-03-03T15:55:44 IST" name="loginWithIncorrectID" finished-at="2022-03-03T15:55:56 IST" duration-ms="11478" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertFalse(Assert.java:67)
at org.testng.Assert.assertFalse(Assert.java:77)
at com.qa.testCases.LoginPageTestScenario2.loginWithIncorrectID(LoginPageTestScenario2.java:52)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginWithIncorrectID -->
        <test-method is-config="true" signature="tearDown()[pri:0, instance:com.qa.testCases.LoginPageTestScenario2@694abbdc]" started-at="2022-03-03T15:55:56 IST" name="tearDown" finished-at="2022-03-03T15:55:57 IST" duration-ms="775" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.qa.testCases.LoginPageTestScenario2 -->
    </test> <!-- TestScreenshot -->
  </suite> <!-- SuiteScreenshot -->
</testng-results>
